### ISSUE TITLE
admin view date and account not found

### ISSUE THREAD

**Issue by bobir01** [begyy/PaycomUz#10]
<img width="1438" alt="image" src="https://github.com/begyy/PaycomUz/assets/68824641/8c1e9d26-0857-4032-af31-0886afc6c8a0">
admin panelga Transaction modelni register qilayotganda modelda yo'q fieldlar bor ekan

**Comment by KarimovMurodilla** [comment]
Fixed ✅

**Comment by KarimovMurodilla** [comment]
Fixed ✅

**Comment by bobir01** [comment]
@KarimovMurodilla Thanks)
