### ISSUE TITLE
Get Statement

### ISSUE THREAD

**Issue by Fakhrillo** [begyy/PaycomUz#12]
Assalamu alaykum, GetStatement uchun method qoldirilmagan ekan, shuni qanday implement qilsam bo'ladi? Javob uchun oldindan rahmat

**Comment by KarimovMurodilla** [comment]
https://github.com/begyy/PaycomUz/blob/08a397b21d4c0d177eddb312f199ec47e78732d5/paycomuz/views.py#L219

Voaleykum assalom. GetStatement metodlarga qo'shilgan. Sizda qanday hatolik chiqdi?

**Comment by Fakhrillo** [comment]
![image](https://github.com/user-attachments/assets/9762b51d-5659-4fde-8d1a-18988606f93b)

Shunaqa error qaytargandi, 3.0 versiya ishlatyotgandim

**Comment by KarimovMurodilla** [comment]
`pip install PaycomUz==3.1`

3.1 versiyasini o'rnatib ko'ring

**Comment by Fakhrillo** [comment]
Ha rahmat, boshida 3.1 bn muammo chiqani un 3 bn ishlab turgandim, 3.1 yaga otkazdim hammasi yaxshi ishlayapti
