### ISSUE TITLE
documentatsiya yozish kere

### ISSUE THREAD

**Issue by begyy** [begyy/PaycomUz#7]
https://begyy.github.io/ClickUz/ shunaqa documentatsiya yozish kere

**Comment by begyy** [comment]
@KarimovMurodilla

**Comment by begyy** [comment]
ilojisi bosa test ham  :)

**Comment by KarimovMurodilla** [comment]
vizov prinyat)

**Comment by KarimovMurodilla** [comment]
Assalomu aleykum. PR chiqarib qoydim, endi uni github ga deploy qivorish kk

**Comment by KarimovMurodilla** [comment]
Assalomu aleykum! Ohirgi commitni kormadizmi?)

**Comment by begyy** [comment]
@KarimovMurodilla Salom qalesiz yaxshimisz hali yoq uspet qilomadim sorry ishla kopayib keti shanba yoki yakshanba korib chiqman

**Comment by begyy** [comment]
@KarimovMurodilla test yozishi bilaszmi?)

**Comment by KarimovMurodilla** [comment]
> @KarimovMurodilla test yozishi bilaszmi?)

Payme ni methodlarini tekshirish uchunmi?

**Comment by begyy** [comment]
> > @KarimovMurodilla test yozishi bilaszmi?)
> 
> Payme ni methodlarini tekshirish uchunmi?

da

**Comment by KarimovMurodilla** [comment]
> > > @KarimovMurodilla test yozishi bilaszmi?)
> > 
> > 
> > Payme ni methodlarini tekshirish uchunmi?
> 
> da

bir vaqt boganda yozib qoyarman

**Comment by begyy** [comment]
https://github.com/begyy/PaycomUz/pull/8
